# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1bbe39b3c1b584f8423151f28e83f6e5f513a4f3c6a9a479109566faa6beeae0826c24b168fb0d41d4803416611e94816f54932f3c882cc2fae7394bb18ca01

test:
  secret_key_base: 8029d7245660a4a3f20bca142c4d661bdf4138bf012af00f75bd045c137f06090185bea81f5fffc9307019ec375c90afe3f448e548f4c305674b097916688af5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
